
const STATUS_OPTIONS=["Available","Monitoring","Interested","Applied","Interview","Offer","Not Available"];
const cfg=window.PAGE_CONFIG||{};
const raw=JSON.parse(document.getElementById("page-data").textContent);
const SEARCH_TEXT=raw.map(r=>Object.values(r).join(" ").toLowerCase());
const storeKey="salama-track-"+(cfg.key||location.pathname);
const favKey=storeKey+"-fav";
let saved={},favorites={};try{saved=JSON.parse(localStorage.getItem(storeKey)||"{}")}catch(e){}try{favorites=JSON.parse(localStorage.getItem(favKey)||"{}")}catch(e){}
const getStatus=r=>saved[r.id]||r.status||"Monitoring";
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
const $=id=>document.getElementById(id);let page=1;let view=localStorage.getItem("salama-view")||"cards";
function uniq(k){return [...new Set(raw.map(x=>x[k]).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b)))}
function fill(id,key,label){$(id).innerHTML=`<option value="">All ${label}</option>`+uniq(key).map(v=>`<option>${esc(v)}</option>`).join("")}
function current(){const term=$("search").value.trim().toLowerCase(),type=$("typeFilter").value,region=$("regionFilter").value,status=$("statusFilter").value,fit=$("fitFilter").value,source=$("sourceFilter").value,fav=$("favOnly").checked;let rows=raw.filter((r,i)=>{const hay=SEARCH_TEXT[i];return(!term||hay.includes(term))&&(!type||r.type===type)&&(!region||r.region===region)&&(!status||getStatus(r)===status)&&(!fit||r.fit===fit)&&(!source||r.source===source)&&(!fav||favorites[r.id])});const sort=$("sortBy").value;const statusRank={"Available":0,"Monitoring":1,"Interested":2,"Applied":3,"Interview":4,"Offer":5,"Not Available":6};rows.sort((a,b)=>{if(sort==="name")return String(a.title).localeCompare(String(b.title));if(sort==="region")return String(a.region).localeCompare(String(b.region))||String(a.title).localeCompare(String(b.title));if(sort==="status")return (statusRank[getStatus(a)]??9)-(statusRank[getStatus(b)]??9)||String(a.title).localeCompare(String(b.title));return (favorites[b.id]?1:0)-(favorites[a.id]?1:0)||(statusRank[getStatus(a)]??9)-(statusRank[getStatus(b)]??9)||String(a.title).localeCompare(String(b.title))});return rows}
function details(r){return (cfg.details||[]).filter(d=>r[d.key]).map(d=>`<div><b>${esc(d.label)}:</b> ${esc(r[d.key])}</div>`).join("")}
function statusClass(st){return st.toLowerCase().replaceAll(" ","-")}
function card(r){const st=getStatus(r);return `<article class="card"><div class="card-head"><div><h2>${esc(r.title)}</h2><div class="sub">${esc(r.subtitle||"")}</div></div><button class="star ${favorites[r.id]?"on":""}" data-fav="${esc(r.id)}" title="Favorite">★</button></div><div class="badges"><span class="badge">${esc(r.type||"Other")}</span><span class="badge ${statusClass(st)}">${esc(st)}</span>${r.fit?`<span class="badge">${esc(r.fit)} fit</span>`:""}</div><div class="details">${details(r)}</div><div class="card-actions"><select class="control status-select" data-id="${esc(r.id)}">${STATUS_OPTIONS.map(x=>`<option ${x===st?"selected":""}>${x}</option>`).join("")}</select>${r.url?`<a class="btn primary" href="${esc(r.url)}" target="_blank" rel="noopener">Open link</a>`:""}</div></article>`}
function table(rows){const cols=[['title','Title'],['subtitle','Organisation'],['type','Type'],['region','Region'],['country','Country'],['fit','Fit'],['status','Status'],['checked','Checked']];return `<div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${c[1]}</th>`).join("")}<th>Link</th></tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${c[0]==='status'?esc(getStatus(r)):esc(r[c[0]]||'')}</td>`).join("")}<td>${r.url?`<a class="btn primary" href="${esc(r.url)}" target="_blank">Open</a>`:""}</td></tr>`).join("")}</tbody></table></div>`}
function render(){const rows=current(),pageSize=parseInt($("pageSize").value||30),pages=Math.max(1,Math.ceil(rows.length/pageSize));if(page>pages)page=pages;const shown=rows.slice((page-1)*pageSize,page*pageSize);$("resultCount").textContent=`Showing ${shown.length} of ${rows.length} matching records — ${raw.length} total`;$("availableCount").textContent=raw.filter(r=>getStatus(r)==="Available").length;$("monitoringCount").textContent=raw.filter(r=>getStatus(r)==="Monitoring").length;$("notAvailableCount").textContent=raw.filter(r=>getStatus(r)==="Not Available").length;$("favoriteCount").textContent=Object.values(favorites).filter(Boolean).length;$("results").className=view==="cards"?"cards":"";$("results").innerHTML=shown.length?(view==="cards"?shown.map(card).join(""):table(shown)):`<div class="empty">No records match the selected filters.</div>`;document.querySelectorAll("select[data-id]").forEach(el=>el.onchange=()=>{saved[el.dataset.id]=el.value;localStorage.setItem(storeKey,JSON.stringify(saved));render()});document.querySelectorAll("button[data-fav]").forEach(el=>el.onclick=()=>{favorites[el.dataset.fav]=!favorites[el.dataset.fav];localStorage.setItem(favKey,JSON.stringify(favorites));render()});$("pagination").innerHTML=pages>1?`<button class="btn" id="prev" ${page===1?"disabled":""}>Previous</button><span class="control">Page ${page} of ${pages}</span><button class="btn" id="next" ${page===pages?"disabled":""}>Next</button>`:"";if($("prev"))$("prev").onclick=()=>{page--;render();scrollTo(0,0)};if($("next"))$("next").onclick=()=>{page++;render();scrollTo(0,0)};document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view))}
function exportCsv(){const rows=current(),keys=[...new Set(rows.flatMap(Object.keys))],q=v=>`"${String(v??"").replaceAll('"','""')}"`;const data=[keys.join(","),...rows.map(r=>keys.map(k=>q(k==="status"?getStatus(r):r[k])).join(","))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+data],{type:"text/csv"}));a.download=(cfg.key||"data")+"-filtered.csv";a.click();URL.revokeObjectURL(a.href)}
fill("typeFilter","type","types");fill("regionFilter","region","regions");fill("fitFilter","fit","fit levels");fill("sourceFilter","source","sources");STATUS_OPTIONS.forEach(v=>$("statusFilter").insertAdjacentHTML("beforeend",`<option>${v}</option>`));["search","typeFilter","regionFilter","statusFilter","fitFilter","sourceFilter","sortBy","pageSize","favOnly"].forEach(id=>$(id).addEventListener(id==="search"?"input":"change",()=>{page=1;render()}));$("exportBtn").onclick=exportCsv;$("resetBtn").onclick=()=>{["search","typeFilter","regionFilter","statusFilter","fitFilter","sourceFilter"].forEach(id=>$(id).value="");$("sortBy").value="priority";$("favOnly").checked=false;page=1;render()};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;localStorage.setItem('salama-view',view);render()});const theme=localStorage.getItem('salama-theme')||'light';document.documentElement.dataset.theme=theme;$("themeBtn").onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('salama-theme',next)};render();
